### PR TITLE
WIP: Produce warning if an issue araises during imports

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
I'm kind of 50/50 to this solution. Maybe a simple warning without pip version produced in the logs would be more clear and concise solution (without calling `_check_pip_version`). If there is any issue with pip imports, we can print just warning and let pip version check on users. 

@frenzymadness WDYT?

**Comment by fridex** [comment]
Manually tested:

```
pip in version '7.1.0' not tested, tested versions: '<=20.2.2,>=9'
Traceback (most recent call last):
  File "./micropipenv.py", line 68, in <module>
    from pip._vendor.packaging.requirements import Requirement
ModuleNotFoundError: No module named 'pip._vendor.packaging.requirements'
```

The point is that `Version`, `__version__` and `SpecifierSet` needed in the `_check_pip_version` function might not be available/importable in all old releases (I haven't check them all)

**Comment by fridex** [comment]
> If there is any issue with pip imports, we can print just warning and let pip version check on users.

See this solution https://github.com/thoth-station/micropipenv/pull/124

**Comment by frenzymadness** [comment]
It might be possible to combine these two options. Let me explain:

* in call of `_check_pip_version`
  * are we able to import the required minimum from pip._vendor?
    * if yes, check the version specifiers and then for:
        * supported pip — do nothing, the problem is probably not related to pip
        * unsupported pip — print the warning
    * if no, print the warning

Texts of the warnings might also reflect the differences — in one case we know that the pip is incompatible and that it probably causes some troubles in other one we don't.

What do you think? Is this overcomplicated?

**Comment by fridex** [comment]
> What do you think? Is this overcomplicated?

IMHO just a simple check should work. The user should be able to trace the error based on the warning/error produced. This is not business logic and having error handling as simple as possible could reduce maintenance cost in this case.

**Comment by frenzymadness** [comment]
I'd continue with #124

**Comment by fridex** [comment]
> I'd continue with #124

Sounds reasonable.

Closing this issue, see #124.

**Pull request closed without merging**
