### PR TITLE
Perform method discovery for requirements sub-command

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/micropipenv/issues/198

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
I have an idea. It seems to me that the method detection - if no method is explicitly specified - is now happening in multiple places in the codebase. For example here: https://github.com/thoth-station/micropipenv/blob/b301125aed01bd73af96c4361df49b28089a47f0/micropipenv.py#L843 and in the new code in this PR.

What about extracting this functionality to a separated function and using it whenever we need to detect the best method for a situation? We can then call this function in `install` and `requrements` functions and set the method accordingly to the result of the new function. Moreover, the order for methods is already there.

**Comment by fridex** [comment]
@frenzymadness sounds good to me 👍🏻  (BTW the `requrements` sub-command does not support `method=requirements` which will need to be handled). Should we close this PR?

**Comment by frenzymadness** [comment]
I've tried to refactor the existing code to a function and use it in both functions where method discovery is needed. See the latest commit. We can squash them then.

**Comment by fridex** [comment]
It looks like Windows test is failing:

```
tests/test_micropipenv.py::test_requirements_autodiscovery_not_found FAILED
```

**Comment by frenzymadness** [comment]
Ok then, let's merge it as is so the refactoring part is separated and we can revert it if needed and still keep the bugfix you've prepared.

**Pull request merged**
