### PR TITLE
Test with pip==21.0

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
Hmmm, where is Travis?

**Comment by fridex** [comment]
> Hmmm, where is Travis?

I see the following message:

```
Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.
```

https://travis-ci.com/github/thoth-station/micropipenv

**Comment by frenzymadness** [comment]
Maybe it's time to migrate to Github actions. We have fedora-python-tox in there https://github.com/fedora-python/tox-github-action/

**Comment by frenzymadness** [comment]
I've run all the tests (tox envs) localy and they are all green so we can merge this and focus on the CI later.

**Comment by fridex** [comment]
> I've run all the tests (tox envs) localy and they are all green so we can merge this and focus on the CI later.

Awesome, I like to see this. pip went through some refactoring after dropping py2 support so I was expecting some internal API changes. Thanks for testing this! :+1: 

BTW do you have a repo where you run the tox environment with GitHub actions?

**Pull request merged**
