### PR TITLE
Version 1.0.4

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/micropipenv/pull/162

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
@frenzymadness PTAL - let's do a patch release to unblock Windows users

**Comment by frenzymadness** [comment]
I'd like to merge #165 first to have this part complete.

**Comment by fridex** [comment]
> I'd like to merge #165 first to have this part complete.

Rebased, PTAL.

**Review by frenzymadness — APPROVED** [review]
Looks good to me!

**Pull request merged**
