### PR TITLE
New Python 3.11, new pip 22.2, new release

### PR DESCRIPTION
**Pull request by frenzymadness**
SSIA

### CODE REVIEW

**Comment by frenzymadness** [comment]
I'm leaving this open even we cannot merge it now. There are two problems we cannot solve here:
1. Github action preparing Python does not support Py 3.11 yet - this is an issue only for Windows.
1. We do have Python 3.11 in fedora-python-tox container image and it's therefore available for the CI but poetry transitively depends on cffi which does not have Python wheels yet and the container does not contain necessary header files for the compilation of cffi. We are able to solve it because we can install additional packages to the container but the compilation spet would make the testing process much slower.

**Comment by frenzymadness** [comment]
Still no wheels for cffi. I'm afraid they'll be waiting for the final release of Python 3.11. I'm gonna run at least one tox environment with Python 3.11 locally.

**Comment by frenzymadness** [comment]
We are compatible with Python 3.11: `py311-piplatest-tomli: commands succeeded`

**Comment by frenzymadness** [comment]
@hroncok wanna take a look?

**Comment by hroncok** [comment]
> @hroncok wanna take a look?

Sorry, this somehow slipped :/

**Pull request merged**
