### PR TITLE
Drop Python 3.6 & pip master branch combo from tests

### PR DESCRIPTION
**Pull request by frenzymadness**
The next release of pip will drop support of Python 3.6.
See: https://github.com/pypa/pip/commit/0252c04a16cd93fe422cebf0b48453b559a2e404

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Thanks for the PR. Why also pip master branch?

**Comment by frenzymadness** [comment]
> Thanks for the PR. Why also pip master branch?

I don't understand the question. The only removed combination is Python 3.6 and pip from its git master branch.

**Review by fridex — APPROVED** [review]
lgtm 👍🏻 thanks!

**Comment by fridex** [comment]
> > Thanks for the PR. Why also pip master branch?
> 
> I don't understand the question. The only removed combination is Python 3.6 and pip from its git master branch.

Sorry, I read it wrong. Thanks again 👍🏻

**Pull request merged**
