### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735914655

### CODE REVIEW

**Review by fridex — APPROVED** [review]
thanks! :+1:

**Comment by bissenbay** [comment]
@fridex @harshad16 We don't have `aicoe-ci.yaml`, `Pipfile` and `Pipfile.lock` in this repo?

**Comment by fridex** [comment]
> @fridex @harshad16 We don't have `aicoe-ci.yaml`, `Pipfile` and `Pipfile.lock` in this repo?

No need for Pipfile/Pipfile.lock (as of now) as pipfile cannot manage pip in the pipenv files.

Support for aicoe-ci is tracked in https://github.com/AICoE/aicoe-ci/issues/40.

**Comment by frenzymadness** [comment]
Could you please explain what this change does? I'm sorry, I don't understand the purpose of this file. We'll maintain micropipenv in the RHEL for the main Python stack (3:6) which means that it might be better to test it there with 3.6 or all available Pythons. Is this possible?

If you use micropipenv with the main Python on RHEL it will be 3.6. You can, of course, install it from PyPI to a virtual environment for whatever Python you want but this case is covered in Travis CI.

Or I might completely misunderstand :)

**Comment by fridex** [comment]
@frenzymadness sorry, we need to be more verbose here. This change is just in `.thoth.yaml` that is a configuration file picked by our bot (@sesheta) and subsequently propagated to a server-side resolver that resolves dependencies. It should not have any affect to micropipenv code or functionality from RHEL/Fedora/... perspective.

The main reason of having `.thoth.yaml` file in this repo are notifications about new pip releases once the workflow will be in place. As of now we use pipenv for dependency update information which does not work when `pip` is in the dependency listing. We plan to switch to a better solution so that we get notifications also about new pip releases. Let me know if more info is needed here.

**Pull request merged**
