### PR TITLE
Run tests with multiple versions of pip

### LINKED ISSUE #64: Testing with various versions of pip
It seems that right now we have only one version of pip in our testing dependencies and moreover this version is not locked. If I am not wrong, the version of pip we are using in tests is the one which virtualenv bundles and it's therefore available in pytest-venv fixture where our test run. Right?

IMHO, this has to be extended if we want to keep backward compatibility and test micropipenv with the latest pip before it's bundled in virtualenv.

What do you think about it? I can try to prepare something. A solution also has to be optional so the tests won't require internet.

### PR DESCRIPTION
**Pull request by frenzymadness**
## Related Issues and Dependencies

Fixes #64 
…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

A testing matrix for multiple versions of pip in combination with multiple Pythons.

### CODE REVIEW

**Comment by frenzymadness** [comment]
I don't understand the configuration of CI in this project but tox works well locally.

In some combinations, there is an error:
```
Building wheels for collected packages: daiquiri, daiquiri
  Building wheel for daiquiri (setup.py) ... done
  Created wheel for daiquiri: filename=daiquiri-2.1.0-py2.py3-none-any.whl size=13400 sha256=b65be8516ca9e095adfdab2faca220927a3c91b5ea2ff67fc4417bc3881a6165
  Stored in directory: /tmp/pip-ephem-wheel-cache-lcsr_o5l/wheels/e0/3e/12/b610ce3283cc6b2d9fa49e5e41ba0ae10ec349f6d054beb87e
  Building wheel for daiquiri (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/pytest-of-lbalhar/pytest-40/test_install_pip_vcs0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-am7oq5ob/daiquiri/setup.py'"'"'; __file__='"'"'/tmp/pip-install-am7oq5ob/daiquiri/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rx7x19gj --python-tag cp39
       cwd: /tmp/pip-install-am7oq5ob/daiquiri/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.9/tokenize.py", line 392, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-am7oq5ob/daiquiri/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for daiquiri
  Running setup.py clean for daiquiri
  ERROR: Command errored out with exit status 1:
   command: /tmp/pytest-of-lbalhar/pytest-40/test_install_pip_vcs0/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-am7oq5ob/daiquiri/setup.py'"'"'; __file__='"'"'/tmp/pip-install-am7oq5ob/daiquiri/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-am7oq5ob/daiquiri
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib64/python3.9/tokenize.py", line 392, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-am7oq5ob/daiquiri/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for daiquiri
Successfully built daiquiri
Failed to build daiquiri
Installing collected packages: python-json-logger, daiquiri
Successfully installed daiquiri-2.1.0 python-json-logger-0.1.11
---------------------------------- pip freeze ----------------------------------
daiquiri==2.1.0
python-json-logger==0.1.11
---------------------------------- pip freeze ----------------------------------
PASSED
```
But it has no impact on the test result.

**Comment by frenzymadness** [comment]
Does CI use the same configuration we have in tox?

**Comment by goern** [comment]
> Does CI use the same configuration we have in tox?

https://github.com/thoth-station/aicoe-ci/blob/master/tasks/pre-commit-check.yaml#L46 is what we want to focus on in the future. If you could recommend a method please do so!

**Comment by fridex** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/zuul/t/local/build/f9d2cc2d0c8d44f983a4ec3c4f4b6905) : FAILURE in 41s

The relevant error log part is:

```
tests/test_micropipenv.py
|  42| def·venv_with_pip(venv):
|    | [NORMAL] PyDocStyleBear:
|    | D205: 1 blank line required between summary line and description (found 0)

tests/test_micropipenv.py
|  42| def·venv_with_pip(venv):
|    | [NORMAL] PyDocStyleBear:
|    | D209: Multi-line docstring closing quotes should be on a separate line

tests/test_micropipenv.py
|  42| def·venv_with_pip(venv):
|    | [NORMAL] PyDocStyleBear:
|    | D400: First line should end with a period (not ',')
```

**Comment by fridex** [comment]
I'll merge this so that we can test micropipenv locally until it the CI gets resolved.

**Comment by fridex** [comment]
> Coala Test failed! Click here

Ah, coala complains. PTAL @frenzymadness

**Pull request merged**
