### PR TITLE
Add Python 3.10 to trove classifiers

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
If we want to, we can start testing on Python 3.11 as well.

**Comment by fridex** [comment]
> If we want to, we can start testing on Python 3.11 as well.

That would be great. 👍🏻 Should we add it in a separate PR?

**Comment by fridex** [comment]
ping @frenzymadness, is this something worth having in the upcoming release? The codebase is already tested with Python 3.10.

**Comment by frenzymadness** [comment]
Let's try it at least. I'm gonna prepare a PR.

**Comment by fridex** [comment]
> Let's try it at least. I'm gonna prepare a PR.

Do you mean Python 3.10 or 3.11? I see you have already done work on Python 3.10:

https://github.com/thoth-station/micropipenv/blob/a6aa43a81afdb56629cdd73094fa061af405edc3/.github/workflows/main.yml#L64-L71

**Comment by frenzymadness** [comment]
Let's see what happens in #216

**Comment by frenzymadness** [comment]
Forget about it for now and do a release, it will take some time to prepare CI for Python 3.11. Sorry for the noise.

**Review by frenzymadness — APPROVED** [review]

**Pull request merged**
