### PR TITLE
Opt out as reviewers for micropipenv

### PR DESCRIPTION
**Pull request by harshad16**
Opt out as reviewers for micropipenv.

## Description

As my focus has shifted a bit and I haven't been able to provide total support in reviewing micropipenv PRs.
I would like to opt out as a reviewer for now and would continue acting as a contributor going further.

Thank you for team to include me as a reviewer.

### CODE REVIEW

**Comment by harshad16** [comment]
@fridex  sent you an invite as a collaborator for this repo only.
please accept it if you would like to be a collaborator for the repo.

**Comment by fridex** [comment]
> @fridex sent you an invite as a collaborator for this repo only. please accept it if you would like to be a collaborator for the repo.

Accepted, thank you. I tend to review PRs from time to time - if you don't see me valuable, feel free to remove it (also anytime in the future). Thanks!

**Comment by frenzymadness** [comment]
Thank you for all the work you did here. I don't know why the bot thinks that the file is invalid. Any idea?

**Comment by harshad16** [comment]
> Thank you for all the work you did here. I don't know why the bot thinks that the file is invalid. Any idea?

It was thinking it was invalid, as fridex was on the collaborator listed 
after including him, it is fixed now.

**Review by frenzymadness — APPROVED** [review]

**Pull request merged**
