### PR TITLE
Produce pip compatibility warning only on issues

### PR DESCRIPTION
**Pull request by fridex**
This change was suggested by Lumír 'Frenzy' Balhar.

## Related Issues and Dependencies

Fixes: #120

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
I've realized that this won't work because if you have older pip (version 8, for example), micropipenv fails on imports not during the main call.

I'll close this and elaborate more in the issue.

**Comment by fridex** [comment]
> I've realized that this won't work because if you have older pip (version 8, for example), micropipenv fails on imports not during the main call.

I liked the check was done on releases we do not test in CI prior to a new release (upper bound). So if a user uses old micropipenv, it is visible in logs - e.g. upgrading pip in s2i where an older micropipenv is installed.

I agree with your point of old pip, however pip in version 9 which is supported dates back to 2016 so older releases seem to be archaic -- yes, I know - obvious upstream vs rhel maintainer argument. The check was done at least on the upper bound of the specification.

**Comment by fridex** [comment]
> The check was done at least on the upper bound of the specification.

To be more specific here - we could add check during imports of `pip` in a similar fashion for older pip releases and keep the check as introduced in this pr for newer releases.

**Comment by fridex** [comment]
Rebased on top of the current master branch with pip version check from the git master branch.

**Review by frenzymadness — APPROVED** [review]
I think we can merge this one.

**Pull request merged**
