### PR TITLE
Produce error message if any issue is raised during pip imports

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/micropipenv/pull/123

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
You are right, this is not our business logic and we should keep it simple so this approach is more than enough for failed imports. Could you just please use f-string in `_LOGGER.error("Check you pip version, supported pip versions: %s", _SUPPORTED_PIP_STR)`

**Comment by fridex** [comment]
> Could you just please use f-string in `_LOGGER.error("Check you pip version, supported pip versions: %s", _SUPPORTED_PIP_STR)`

f-strings are [Python 3.6 feature](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498). We claim Python 3.5 in setup.py:

https://github.com/thoth-station/micropipenv/blob/2e7c8720d1a094f6a9e3826c758f547905eba5be/setup.py#L42

Do we have use case to keep it (even though we do not run Python 3.5 tests) or remove Python 3.5 from setup.py?

(I would say the lazy string expansion in logger is not that relevant in this case.)

**Comment by frenzymadness** [comment]
Python 3.5 EOL date is 2020-09-13 so I think we can freely remove it.

**Comment by fridex** [comment]
> Could you just please use f-string in `_LOGGER.error("Check you pip version, supported pip versions: %s", _SUPPORTED_PIP_STR)`

Done in 7c8f735.

**Review by frenzymadness — APPROVED** [review]

**Pull request merged**
