### PR TITLE
Fix support for subdirectories in VCS requirements

### LINKED ISSUE #236: Micropipenv ignores subdirectory for VCS packages.
**Describe the bug**
Micropipenv ignores subdirectory for VCS packages.

**To Reproduce**
- Generate a Pipenv.lock using git vcs and a subdirectory:
  ```bash
  pipenv install git+ssh://git@github.com/RidgeRun/gstd-1.x.git@v0.13.2#egg=pygstc\&subdirectory=libgstc/python
  ```
- try to run micropipenv
  ```bash
  micropipenv install
  ```

Error : 
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r4wwbzy1/pygstc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r4wwbzy1/pygstc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r4wwbzy1/pygstc/pip-egg-info
         cwd: /tmp/pip-install-r4wwbzy1/pygstc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-r4wwbzy1/pygstc/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
micropipenv navigates to the subdirectory to find the setup.py

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by frenzymadness**
## Related Issues and Dependencies

Fixes #236 
…

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
One of the tests needed a fix. See the last commit.

**Comment by frenzymadness** [comment]
CI is green, @MaxandreOgeret do you want to do a review and/or test it?

**Comment by MaxandreOgeret** [comment]
@frenzymadness Will review and test.

**Comment by frenzymadness** [comment]
> But I think it should be added to unit tests as well.

What do you mean? There is a new test for this change.

**Comment by MaxandreOgeret** [comment]
My bad, got mixed up. Looks all good for me.

**Comment by frenzymadness** [comment]
I'm gonna merge it and try my first release. Thanks a lot for your help!

**Pull request merged**
