### PR TITLE
Fix python version to run testsuite correctly

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
recheck

**Comment by goern** [comment]
@pacospace  why is this advise still running?!

**Comment by pacospace** [comment]
> @pacospace why is this advise still running?!

Good question, I don't see logs that go back webhook receiver after adviser run.

**Comment by pacospace** [comment]
> > @pacospace why is this advise still running?!
> 
> Good question, I don't see logs that go back webhook receiver after adviser run.

I found the issue!

**Comment by fridex** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/zuul/t/local/build/3c413406d15d4dc48e0932d7704ce6db) : FAILURE in 45s
> * [thoth-pytest ](https://managesf.thoth-station.ninja/zuul/t/local/build/ec74e720abca443b8fcde40bb8f0f4b7) : FAILURE in 1m 31s

The error seems to be specific to containerized CI run:

```
    os.environ['HOME'] = pwd.getpwuid(os.getuid())[5]
KeyError: 'getpwuid(): uid not found: 1008520000'
```

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
This is part of #22

**Pull request closed without merging**
