### PR TITLE
Version 1.1.1

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/micropipenv/pull/188

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/assign @frenzymadness 

PTAL, I was not sure if this version should be 1.1.1 or 1.2.0 semantically.

**Review by frenzymadness — CHANGES_REQUESTED** [review]
I agree with 1.1.1 - we are basically fixing a bug in poetry implementation which is what is the last number for. But you have forgotten to change the version in the main module.

**Comment by fridex** [comment]
> I agree with 1.1.1 - we are basically fixing a bug in poetry implementation which is what is the last number for. But you have forgotten to change the version in the main module.

Thanks for the catch 👍🏻 Adjusted in 637c2ee. PTAL

**Review by frenzymadness — APPROVED** [review]
Looks good to me.

**Pull request merged**
