### PR TITLE
Test check_pip_version with the pip from the venv

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: https://github.com/thoth-station/micropipenv/issues/169

### CODE REVIEW

**Comment by frenzymadness** [comment]
This is now expected to fail with `-piplatest-` environment until we merge #167 .

**Comment by fridex** [comment]
Nice catch, I think we can have this in 👍🏻 

/approve

**Comment by frenzymadness** [comment]
Thanks, I'm gonna rebase it and might change the docstrings as well.

**Review by fridex — APPROVED** [review]

**Comment by frenzymadness** [comment]
Ah, okay, no problem, I'm gonna open a next PR anyway for mypy issues on Windows.

**Comment by fridex** [comment]
> Ah, okay, no problem, I'm gonna open a next PR anyway for mypy issues on Windows.

Sorry if I was too quick. I thought it was ready.

**Comment by frenzymadness** [comment]
I'm sorry, I should communicate better and open a draft PR in the first place.

**Pull request merged**
