### PR TITLE
adding initial support for poetry groups, beginning testing

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
## Related Issues and Dependencies

Addresses [Groups support in Poetry lock files #185 ](https://github.com/thoth-station/micropipenv/issues/185)

## This introduces a breaking change

- Not sure, opening pr while undergoing testing --> /hold

## This Pull Request implements

Adding support for poetry dependency groups as introduced in v1.20a2 of poetry (preview version). 

## Description

Current change is to the parsing of the pyproject.toml file, where it will look for additional groups. Poetry group syntax for dependencies looks like `[tools.poetry.group.<group_name>.dependencies]`. It also introduces an alternative for the dev-dependencies by defining them as a group, like so: `[tools.poetry.group.dev.dependencies]`, and these are included in the adjustments to the `micropipenv.py` file. The original issue above mentions that we will need to handle dev dependencies in the `poetry.lock` file, which I am not sure about, because I thought that was included by checking the "category" of entries in that file are `main` or `dev`, and the groups themselves aren't listed in the `poetry.lock` file.

Original PR started from old version of upstream master, migrated here so there are less changes. Additional ran pre-commit for entire repo, so there are unrelated lining changes in `setup.cfg`.

### CODE REVIEW

**Comment by goern** [comment]
any updates?

**Comment by Gregory-Pereira** [comment]
Currently paused, I am finishing up deploying argocd-notifications for operate-first right now, but this is my next priority after that. I need to debug the 4 tests that failed.

**Comment by frenzymadness** [comment]
Note that there is a problem currently with pip 9 which seems to no longer work with the latest setuptools so some of the failures might not be caused by your changes. We're gonna fix that soon hopefully in #219 so just a rebase might help then.

**Comment by Gregory-Pereira** [comment]
It looks like 2 of the three tests that failed here were using pip90, not sure if it's to do with those setup tools errors, ill comb through the logs more carefully, and if so I will wait on #219 merging. One of them is failing with pip latest as well so ill need to see what happened there. And I will make sure to rebase it gets merged, thanks!

**Comment by frenzymadness** [comment]
Poetry 1.2 is still in alpha and the last release is from August last year so there is no rush here. On the other hand, in [the docs](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups) they say:

> Any dependency declared in the dev-dependencies section will automatically be added to a dev group.

and

> Poetry will slowly transition away from the dev-dependencies notation which will soon be deprecated, so it’s advised to migrate your existing development dependencies to the new group notation.

Which IMO means that our implementation of dev and default groups should be extended to count with more than just these two groups. I'm afraid that this change will mean that our interface will be different for poetry and pipenv.

**Comment by frenzymadness** [comment]
@Gregory-Pereira I see that there is new Poetry 1.2.0b2 released 4 days ago. Do you plan to continue with this PR?

**Comment by Gregory-Pereira** [comment]
Thanks for the update. I will be picking this back up shortly, just some other work is currently taking priority.
/remove-lifecycle rotten
/remove-lifecycle stale

**Pull request closed without merging**
