### PR TITLE
Test with pip<=21.1.1

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
There are a lot of mypy errors. I'm not sure yet where are they coming from.

**Comment by fridex** [comment]
> There are a lot of mypy errors. I'm not sure yet where are they coming from.

It's not clear to me why windows tests fail. Tests report `Error: The operation was canceled.`. A search for a similar issue on GitHub pointed to https://github.com/actions/virtual-environments/issues/1918 (memory issues). Not sure if that's the case for us (?).

**Comment by fridex** [comment]
> > There are a lot of mypy errors. I'm not sure yet where are they coming from.
> 
> It's not clear to me why windows tests fail. Tests report `Error: The operation was canceled.`. A search for a similar issue on GitHub pointed to [actions/virtual-environments#1918](https://github.com/actions/virtual-environments/issues/1918) (memory issues). Not sure if that's the case for us (?).

Hm, could these tests be terminated as https://github.com/thoth-station/micropipenv/pull/167/checks?check_run_id=2557409417 is failing? Then I see your point about mypy errors.

**Comment by frenzymadness** [comment]
I'm running all the tests locally so we can merge this and make the new test from #170 happy and we can then focus on the mypy errors on widows.

**Comment by frenzymadness** [comment]
Also, there are many changes in typing in the latest pip so the errors might come from some difference there.

**Review by frenzymadness — APPROVED** [review]
I can confirm that all tests are passing locally.

**Comment by fridex** [comment]
Great, thanks for confirming. Let's merge then. 👍🏻

**Pull request merged**
