### PR TITLE
Add a link to Bodhi

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
@frenzymadness not sure if Bodhi is more relevant than Koshei in this case.

**Comment by frenzymadness** [comment]
Honestly, I'd link to the RPM source repository. Overview there contains the latest RPM version for each supported Fedora and also information about updates in testing - https://src.fedoraproject.org/rpms/micropipenv
Bodhi contains only updates for stable releases (or for the future release after Bodhi is activated for it before the final release) and Koschei contains only rebuilds of micropipenv whenever its dependencies changes but those builds are not included in the Fedora.

What do you think about it?

**Comment by fridex** [comment]
> What do you think about it?

Updated, PTAL.

**Review by frenzymadness — APPROVED** [review]
Perfect!

**Pull request merged**
