### PR TITLE
Version 1.0.2

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/approve

CI is green, I'll merge this and do the release.

**Comment by frenzymadness** [comment]
Thankk you!

Fedora updates: https://bodhi.fedoraproject.org/updates/?packages=micropipenv

**Comment by fridex** [comment]
> Fedora updates: https://bodhi.fedoraproject.org/updates/?packages=micropipenv

Awesome, thanks! :+1:

**Pull request merged**
