### PR TITLE
Version 0.2.0

### PR DESCRIPTION
**Pull request by fridex**
Depends-On: #69 #68 #67

### CODE REVIEW

**Comment by goern** [comment]
I have put all the linked issues in https://github.com/orgs/thoth-station/projects/1#column-9239965 so that we have a list of release blockers.

**Comment by fridex** [comment]
I think we are good to go with 0.2.0 release. I've verified the test suite locally (locally until we setup CI).

PTAL @frenzymadness

**Comment by frenzymadness** [comment]
Please, don't do a release now, I've probably found a bug. I'll open an issue.

**Comment by fridex** [comment]
> Please, don't do a release now, I've probably found a bug. I'll open an issue.

Ack, thanks! Marking back WIP.

**Comment by fridex** [comment]
Refreshing. @frenzymadness with #76, are we good to go with this release?

**Comment by frenzymadness** [comment]
The tests are green locally so I think we are ready for a new release.

**Comment by goern** [comment]
so https://github.com/orgs/thoth-station/projects/1#card-38568143 is done? @fridex

**Comment by fridex** [comment]
> The tests are green locally so I think we are ready for a new release.

The new release v0.2.0 is [available on PyPI](https://pypi.org/project/micropipenv/0.2.0/), I've also created a [GitHub release](https://github.com/thoth-station/micropipenv/releases/tag/v0.2.0)..

**Comment by fridex** [comment]
> so https://github.com/orgs/thoth-station/projects/1#card-38568143 is done? @fridex

Yes, it's done. I'll adjust our s2i images in a few secs so we start using this release.

**Comment by frenzymadness** [comment]
RPM updates:
- rawhide - https://bodhi.fedoraproject.org/updates/FEDORA-2020-a3f8c88623
- f32 - https://bodhi.fedoraproject.org/updates/FEDORA-2020-cfa1ad2046
- f31 - https://bodhi.fedoraproject.org/updates/FEDORA-2020-65a30226e6

**Pull request merged**
