### PR TITLE
Use setup.cfg

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
This together with https://github.com/thoth-station/kebechet/issues/922 could enable bots to perform automatic releases.

**Review by frenzymadness — APPROVED** [review]
Looks good to me. It might make sense to compare old and new sdist especially metadata they contain before you do a new release.

**Comment by fridex** [comment]
> Looks good to me. It might make sense to compare old and new sdist especially metadata they contain before you do a new release.

Good point. Created sdist with the current master and another one with this patch applied (diff on unpacked sdists):

```
$ diff -qr dist_setup.cfg/ dist_setup.py 
Files dist_setup.cfg/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt and dist_setup.py/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt differ
Files dist_setup.cfg/micropipenv-1.2.0/setup.cfg and dist_setup.py/micropipenv-1.2.0/setup.cfg differ
Files dist_setup.cfg/micropipenv-1.2.0/setup.py and dist_setup.py/micropipenv-1.2.0/setup.py differ
$ diff -Naur dist_setup.cfg/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt dist_setup.py/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt  
--- dist_setup.cfg/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt	1970-01-01 01:00:00.000000000 +0100
+++ dist_setup.py/micropipenv-1.2.0/micropipenv.egg-info/SOURCES.txt	1970-01-01 01:00:00.000000000 +0100
@@ -5,7 +5,6 @@
 README.rst
 micropipenv.py
 pyproject.toml
-setup.cfg
 setup.py
 micropipenv.egg-info/PKG-INFO
 micropipenv.egg-info/SOURCES.txt
```

The difference between `setup.cfg` and `setup.py` is this patch.

Maybe a cleaner solution is to use wheels (given the static metadata):

```
$ diff -qr setup.cfg_wheel setup.py_wheel
```

Both look equivalent.

**Comment by fridex** [comment]
> Looks good to me.

Prow seems to be down, merging manually.

**Pull request merged**
