### PR TITLE
Poetry support

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: #22 #24 #23
Depends-On: #26 (used as a base for this patch, see 1a0db43 for actual changes made)

## This introduces a breaking change

- [ ] Yes
- [x] No

## Poetry support

This change introduces support for lock files as produced by Poetry. Files poetry.lock and pyproject.toml are parsed into internal data structure compatible with Pipfile.lock as produced by Pipenv. Dependencies are installed as Pipfile.lock would be used.

The Pipfile.lock is printed to stderr and optionally stored to the resulting container build to assist Thoth's analyzers. This helps with software stack quality observation aggregation (build log analysis, container image analysis) on Thoth side.

## pip and pip-tools support

This pull request implements the handling of requirements as supported by `pip`, `pip-tools` and Thoth.

If the requirements file states all the packages in a pinned version with hashes, it is parsed using pip's internal routines and transformed into an internal structure compatible with Pipfile.lock format. Requirements described in this internal structure are subsequently installed as if Pipfile.lock would be used. The corresponding content of Pipfile.lock file is printed to stderr and stored in the container with the application during the build process. This enables Thoth analyzers (container image analysis) to find out what packages were actually used during the application build and simplifies build breaker ananlyses on Thoth side.

If the requirements file does not state fully pinned down version, pip is executed as in case of the current Python s2i approach - pip's resolver resolves the application stack as specified in requiqurements.txt file. A verbose warning is used to notify user about building an application without a lock file (strongly discouraged approach causing issues). The final software stack installed is printed into build logs in a form of `pip freeze` to keep track of installed packages and to simplify analyzers on Thoth's side.

### CODE REVIEW

**Comment by fridex** [comment]
No longer related.

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
> Build failed.
> 
> * [thoth-pytest ](https://managesf.thoth-station.ninja/zuul/t/local/build/4bd5d1a5c13f4378b705ecee3acd5142) : FAILURE in 1m 43s

This seems to be related to a containerized run of tests. I locally tests pass on both, s2i-thoth-ubi8-py36 an s2i-thoth-f31-py37.

**Comment by fridex** [comment]
> Should we not have a python version specified in the Pipfile of the component ?

It will cause issues once we run tests in different environments with different Python interpreter versions (s2i-thoth-ubi8-py37, s2i-thoth-ubi8-py36, ..).

**Comment by harshad16** [comment]
> > Should we not have a python version specified in the Pipfile of the component ?
> 
> It will cause issues once we run tests in different environments with different Python interpreter versions (s2i-thoth-ubi8-py37, s2i-thoth-ubi8-py36, ..).

i was thinking if a repo requires python37 then we configure zuul for it. 
In .zuul.yaml the check would be configured to thoth-pytest-python37.

**Comment by fridex** [comment]
> > > Should we not have a python version specified in the Pipfile of the component ?
> > 
> > 
> > It will cause issues once we run tests in different environments with different Python interpreter versions (s2i-thoth-ubi8-py37, s2i-thoth-ubi8-py36, ..).
> 
> i was thinking if a repo requires python37 then we configure zuul for it.
> In .zuul.yaml the check would be configured to thoth-pytest-python37.

I don't see the direct value for it - there would be a need to patch Pipfile relock Pipfile.lock for another Python interpreter version.  IMHO its OK to have python requirements for our components as we run them on a specific Python interpreter. For micropipenv it's slightly different - we want to support multiple Python versions, so having the Python requirement in the Pipfile seems to be redundant and can complicate things.

**Comment by harshad16** [comment]
> > > > Should we not have a python version specified in the Pipfile of the component ?
> > > 
> > > 
> > > It will cause issues once we run tests in different environments with different Python interpreter versions (s2i-thoth-ubi8-py37, s2i-thoth-ubi8-py36, ..).
> > 
> > 
> > i was thinking if a repo requires python37 then we configure zuul for it.
> > In .zuul.yaml the check would be configured to thoth-pytest-python37.
> 
> I don't see the direct value for it - there would be a need to patch Pipfile relock Pipfile.lock for another Python interpreter version. IMHO its OK to have python requirements for our components as we run them on a specific Python interpreter. For micropipenv it's slightly different - we want to support multiple Python versions, so having the Python requirement in the Pipfile seems to be redundant and can complicate things.

okay, that makes sense, thanks for the explanation. 
I will merge this :+1:

**Pull request merged**
