### PR TITLE
Install dependencies iterativelly with a fallback

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: #12 

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
PTAL @4n4nd (I cannot assign as a reviewer for some reason).

The final algorithm is slightly more sophisticated than the one we discussed. We maintain a queue with packages to install and an integer how many times the given package was tried to be installed but failed. If we succeed with installation, we clear all error flags. If we fail an installation, we increment the error counter and push the package to be installed to the back of the queue. We fail if we tried to install all the packages but failed. This way we can also handle cyclic errors in installation. See comments in the source code.

I tried to test this change on the prometheus-anomaly-detector - the installation process seems to be correctly handled with the installation logic described above, but I'm getting the following error:

```
Collecting fbprophet==0.5 (from -r /tmp/requirements.txtrullg30l (line 2))
  Using cached https://files.pythonhosted.org/packages/33/fb/ad98d46773929079657706e6b2b6e366ba6c282bc2397d8f9b0ea8e5614c/fbprophet-0.5.tar.gz
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    ERROR: Complete output from command /home/fpokorny/git/thoth-station/micropipenv/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vx6jbmxh/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ucs5_t8f/install-record.txt --single-version-externally-managed --compile --install-headers /home/fpokorny/git/thoth-station/micropipenv/venv/include/site/python3.7/fbprophet:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/fpokorny/git/thoth-station/micropipenv/venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vx6jbmxh/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ucs5_t8f/install-record.txt --single-version-externally-managed --compile --install-headers /home/fpokorny/git/thoth-station/micropipenv/venv/include/site/python3.7/fbprophet" failed with error code 1 in /tmp/pip-install-vx6jbmxh/fbprophet/
```

Before I invest time into this, do you have some pointers what could be wrong? I'm running this on my machine - fedora 31 + py 3.7.

BTW logs will be more verbose now, but that's good for Thoth :) as we parse them. I hope it will not bother you that much :)

**Comment by fridex** [comment]
> Before I invest time into this, do you have some pointers what could be wrong? I'm running this on my machine - fedora 31 + py 3.7.
> 

When digging into another issue I realized I don't have python3 header files on my laptop (I freshly reinstalled the OS recently). Now the installation process works as expected.

**Comment by 4n4nd** [comment]
> BTW logs will be more verbose now, but that's good for Thoth :) as we parse them. I hope it will not bother you that much :)

That is awesome :+1: 

> When digging into another issue I realized I don't have python3 header files on my laptop (I freshly reinstalled the OS recently). Now the installation process works as expected.

Great. As long as it works.

**Comment by harshad16** [comment]
> The final algorithm is slightly more sophisticated than the one we discussed. We maintain a queue with packages to install and an integer how many times the given package was tried to be installed but failed. If we succeed with installation, we clear all error flags. If we fail an installation, we increment the error counter and push the package to be installed to the back of the queue. We fail if we tried to install all the packages but failed. This way we can also handle cyclic errors in installation. See comments in the source code.

This looks great :+1:

**Pull request merged**
