### PR TITLE
Fix regression for VCS requirements with ref and add some tests

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes: https://github.com/thoth-station/micropipenv/issues/239

Originaly fixed in: https://github.com/thoth-station/micropipenv/pull/40
Reintroduced in: https://github.com/thoth-station/micropipenv/pull/237

### CODE REVIEW

**Comment by lcy0321** [comment]
Thanks for fixing this issue!

I see there is already a test case `test_install_pipenv_vcs_editable()`. In my opnion, would it be better to create a test case similiar to it, or just extend it to cover this situation?

And of course, the current test in this PR is also fine.

**Comment by frenzymadness** [comment]
The failed test had nothing to do with this change. A fix for it is in the latest commit. I'm gonna take a look at the mentioned test we can possibly extend.

**Comment by frenzymadness** [comment]
> I see there is already a test case `test_install_pipenv_vcs_editable()`. In my opnion, would it be better to create a test case similiar to it, or just extend it to cover this situation?

Now I see that we cannot use the test to test this bugfix. The problem is that micropipenv provides the packages to underlying pip one by one when installing all the dependencies which means that newlines do not play any role in the input provided to pip. That's also the reason why none of the tests uncovered the problem - it happens only when multiple packages are dumped to one file together - only then you can see the problem caused by wrong-placed newlines.

**Comment by frenzymadness** [comment]
Is anybody interested in a review?

**Review by lcy0321 — APPROVED** [review]

**Pull request merged**
