### PR TITLE
Revisit setup.py structure

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: #62

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
We could exec micropipenv.py as it is guarded with ``__name__ == __main__`` and obtain title, version and other info from there.

@goern @frenzymadness It might be also good idea to relicense to LGPLv3+?

**Comment by frenzymadness** [comment]
What about creating a new module for version which then setup.py and micropipenv.py can import? Executing micropipenv to get the version might fail on imports when some dependencies will be missing.

What is the reason for license change?

**Comment by frenzymadness** [comment]
> What about creating a new module for version which then setup.py and micropipenv.py can import? Executing micropipenv to get the version might fail on imports when some dependencies will be missing.

But it would mean we should change micropipenv to package with multiple modules and we don't want to do that I assume. Another way might be to use a regular text file but it would mean to open/close it every time micropipenv runs. Any other idea?

**Comment by fridex** [comment]
> What is the reason for license change?

Allow users to integrate using a lib but still let them have their part closed.


> But it would mean we should change micropipenv to package with multiple modules and we don't want to do that I assume. Another way might be to use a regular text file but it would mean to open/close it every time micropipenv runs. Any other idea?

I would like to keep micropipenv as one file, it can be [handy when building applications](https://github.com/fridex/playground/blob/735512b35b83941774930b8c3d3399cb621afe86/tensorflow-matmul/Dockerfile#L8). The only dependency not guarded with `ImportError` (outside of Python's standard lib) is pip:

https://github.com/thoth-station/micropipenv/blob/7674419889013d652f340fc7ba25aa0e83a599d3/micropipenv.py#L62-L82

AFAIK pip is not a dependency of setuptools. Will it be a big problem if we rely on pip's presence in `setup.py`? We can print out a descriptive error message if pip is not installed (or in an unsupported version `<9`).

**Comment by fridex** [comment]
> Any other idea?

Another way is to [import everything programmatically](https://docs.python.org/3/library/importlib.html) only if running micropipenv or using it as a library.

**Comment by goern** [comment]
I'm good on the relicensing.

**Pull request merged**
