### PR TITLE
Fix no-default no-dev combinations for poetry markers

### PR DESCRIPTION
**Pull request by frenzymadness**
Created on top of the #194 so this PR should be merged as the second.

## Related Issues and Dependencies

#193 

## This introduces a breaking change

- [ ] Yes
- [X] No

My implementation of poetry markers did not count with the fact that the default or devel packages might be missing based on the options users use. This is now fixed and all the tests covers also no-dev no-default options.

### CODE REVIEW

**Comment by fridex** [comment]
@frenzymadness #194 is now merged. Do you think this is ready to be included in v1.1.2 or should we wait?

**Comment by frenzymadness** [comment]
This PR has been a draft just because it needed a rebase. I believe that it's ready.

**Comment by frenzymadness** [comment]
There is also a new test using reproducer configuration from the reporter.

**Review by fridex — APPROVED** [review]
Very nice, thanks for the work 💯 👍🏻

**Pull request merged**
