### PR TITLE
Test with pip==22.0.3

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
pip 22.0.2 is already available, restarting test jobs.

**Comment by frenzymadness** [comment]
I'm gonna take a look at what is happening there. There is an error:
```
2022-01-30T12:55:39.4279243Z 01-30-22 12:55:39 micropipenv  DEBUG  Requirements will be installed using ['/tmp/tmpj92t3a4i/bin/pip3', 'install', '--no-deps', '--disable-pip-version-check', '-r', '/tmp/requirements_micropipenv-8g0w84bs.txt']
2022-01-30T12:55:39.4279815Z 01-30-22 12:55:39 micropipenv  INFO   Installing 'daiquiri'
2022-01-30T12:55:39.8142400Z Usage: pip3 [options]
2022-01-30T12:55:39.8148635Z 
2022-01-30T12:55:39.8157494Z ERROR: Invalid requirement: --index-url
2022-01-30T12:55:39.8158139Z pip3: error: --index-url option requires 1 argument
2022-01-30T12:55:39.8158681Z 
2022-01-30T12:55:39.8711145Z 01-30-22 12:55:39 micropipenv  WARNING Failed to install 'daiquiri', will try in next installation round...
```
I have to reproduce the problem locally to see what's inside the generated file.

**Comment by frenzymadness** [comment]
I was wrong, the error is from a negative test we have there. The real error is:
```
Successfully installed pip-22.0.2
01-31-22 08:10:09 micropipenv  DEBUG  Debug mode is on.
01-31-22 08:10:09 micropipenv  DEBUG  Running 'install' with arguments {'deploy': False, 'dev': False, 'method': 'requirements', 'pip_args': []}
01-31-22 08:10:09 micropipenv  DEBUG  Found 'requirements.txt' in '/home/lbalhar/Software/micropipenv/tests/data/install/requirements'
01-31-22 08:10:09 micropipenv  WARNING pip in version '22.0.2' not tested, tested versions: '>=9,<=22.0'
Traceback (most recent call last):
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 392, in _instantiate_package_finder
    return PackageFinder(find_links=[], session=pip_session, index_urls=_DEFAULT_INDEX_URLS)  # type: ignore
TypeError: PackageFinder.__init__() got an unexpected keyword argument 'find_links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 1315, in <module>
    return_code = main()
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 1301, in main
    handler(**arguments)
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 915, in install
    install_requirements(pip_bin, pip_args=pip_args)
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 848, in install_requirements
    pipfile_lock = _requirements2pipfile_lock(requirements_txt_path)
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 533, in _requirements2pipfile_lock
    finder = _instantiate_package_finder(pip_session)
  File "/home/lbalhar/Software/micropipenv/micropipenv.py", line 413, in _instantiate_package_finder
    return PackageFinder.create(
TypeError: PackageFinder.create() missing 1 required keyword-only argument: 'use_deprecated_html5lib'
FAILED
```

**Comment by frenzymadness** [comment]
https://github.com/pypa/pip/blob/main/NEWS.rst#features
https://github.com/pypa/pip/blob/main/src/pip/_internal/index/package_finder.py#L626
https://github.com/pypa/pip/commit/bf5f4008e7fe421508950763a0101e78a340f33a

I think we can enable html5lib for now and let pip devs fix all possible issues with stdlib HTML parser and disable it later, what do you think? It seems to me that the easiest way is to have a different set of kwargs for Packagefinder for different pip versions.

**Comment by fridex** [comment]
Wow @frenzymadness, thanks for such a quick feedback and digging into this 👍🏻 



> I think we can enable html5lib for now and let pip devs fix all possible issues with stdlib HTML parser and disable it later, what do you think? It seems to me that the easiest way is to have a different set of kwargs for Packagefinder for different pip versions.

+1, sounds good to me

**Comment by frenzymadness** [comment]
I'm working on this right now and I've changed my mind. I'd rather not change pip's defaults. It's up to our users which pip version they have in background and if our tests pass with the new default HTML parser, there is no reason to change it – moreover, we can help pip devs with testing this change here.

There is a new version 22.0.3 so I'm gonna force-push the changes soon. Version 22 also officially does not support Python 3.6 so if it fails, we might need to remove that combination from the CI.

**Comment by frenzymadness** [comment]
All green!

**Comment by fridex** [comment]
> All green!

Thanks a lot for the changes, they look very reasonable. Feel free to approve changes if you see they can go in 👍🏻 (I cannot approve my own PR) 

/lgtm

**Review by frenzymadness — APPROVED** [review]

**Pull request merged**
