### PR TITLE
Version 0.5.0

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
CC @tumido

**Comment by tumido** [comment]
Thank you! :heart:

**Comment by frenzymadness** [comment]
There is a one problem in the newest version I did not realize before. Because Fedora doesn't have pytest-venv as an RPM package and because there is no Internet access during the build, I had to skip all `test_install_*` tests but now there is the direct import `from pytest_venv import VirtualEnvironment` in `conftest.py` so I have to package pytest-venv for Fedora before I'll be able to update micropipenv itself.

It also means that we won't be able to run tests in RHEL package but it's not that unusual.

**Comment by fridex** [comment]
> There is a one problem in the newest version I did not realize before. Because Fedora doesn't have pytest-venv as an RPM package and because there is no Internet access during the build, I had to skip all `test_install_*` tests but now there is the direct import `from pytest_venv import VirtualEnvironment` in `conftest.py` so I have to package pytest-venv for Fedora before I'll be able to update micropipenv itself.
> 
> It also means that we won't be able to run tests in RHEL package but it's not that unusual.

We can [mark tests as online/offline](https://docs.pytest.org/en/stable/example/markers.html) if that would help you. The pytest-venv can be imported in a try-except block and have `PIP_VERSION` set also conditionally. Would that help on your side?

**Pull request merged**
