### PR TITLE
Do not process entries from poetry.lock until their category is known

### PR DESCRIPTION
**Pull request by frenzymadness**
## Related Issues and Dependencies

https://github.com/thoth-station/micropipenv/issues/295

Let's see what this change will break. I expect possible incompatibility with older poetry.

### CODE REVIEW

**Comment by frenzymadness** [comment]
Now is the time to check the failures and see whether the code is wrong or the test is wrong.

**Comment by frenzymadness** [comment]
It seems that the new test with complex dependencies is not compatible with Python <= 3.7. Fixed.

**Comment by frenzymadness** [comment]
This is a big change. A review is necessary. Cc: @fridex @yrro

**Comment by yrro** [comment]
I think my pyproject.toml and lockfile made it into the tests for this PR. But I hope I can give it a manual test on my proejct some time this week.

**Comment by frenzymadness** [comment]
Thank you both. Sam is correct - his configuration is now part of the tests.

**Comment by frenzymadness** [comment]
Or we can test it out there in the wild with a new release :thinking:

**Comment by frenzymadness** [comment]
All right, let's give it a try.

**Pull request merged**
