### PR TITLE
Remove __all__

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by frenzymadness** [comment]
Could you please describe why micropipenv needs this? In general, is it a good idea to use `from micropipenv import *`?

In my opinion, we can completely remove `__all__` variable which means that potential `from micropipenv import *` will import all names without `_` suffix.

**Comment by fridex** [comment]
> Could you please describe why micropipenv needs this? In general, is it a good idea to use `from micropipenv import *`?
> 
> In my opinion, we can completely remove `__all__` variable which means that potential `from micropipenv import *` will import all names without `_` suffix.

Some documentation and IDE tools use it so I tend to include it in sources. But I think we can remove it completely for micropipenv :+1:

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
regate

**Pull request merged**
