### PR TITLE
Test with tomli

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## Description

Check if micropipenv is compatible with [tomli](https://pypi.org/project/tomli/).

### CODE REVIEW

**Comment by frenzymadness** [comment]
I've tried to reproduce the error and it seems that the unencrypted `git://` protocol is no longer supported, see https://github.blog/2021-09-01-improving-git-protocol-security-github/
We should change all `git://` to `https://`. I'm running the tests locally for one of the new environments with this change applied and I'll see what happens.

**Comment by frenzymadness** [comment]
And the error is: `module 'tomli' has no attribute 'TomlDecodeError'`. It seems that the name in `tomli` is different (`TOMLDecodeError`): https://github.com/hukkin/tomli/blob/5701c0be3a76322372f58af0e19163037fec7663/src/tomli/_parser.py#L49

**Comment by frenzymadness** [comment]
We can handle this in `_import_toml` or we can open an upstream issue - it might make sense to create an alias to have the same exception name in these backends. What do you think?

**Comment by fridex** [comment]
Thanks for checking this! 👍🏻 

> We can handle this in `_import_toml` or we can open an upstream issue - it might make sense to create an alias to have the same exception name in these backends. What do you think?

+1, might be a good idea. Let's see what's the upstream opinion on this.

**Comment by frenzymadness** [comment]
Upstream issue: https://github.com/hukkin/tomli/issues/167

**Comment by frenzymadness** [comment]
The issue has been closed. We have to handle this here. Do you wanna do it or should I take a look?

**Comment by fridex** [comment]
> The issue has been closed. We have to handle this here. Do you wanna do it or should I take a look?

Oh, that's a pity. It might be good to have it eventually backward compatible with (older) tomli releases anyway if tomli support will be considered. Feel free to take it if you want 👍🏻 

BTW there are also other libraries that manipulate with TOML besides pytoml and toml which micropipenv currently supports - [rtoml](https://pypi.org/project/rtoml), [pytomlpp](https://pypi.org/project/pytomlpp/), [qtoml](https://pypi.org/project/qtoml/), [tomlkit](https://pypi.org/project/tomlkit/) (from tomli docs). It looks like [tomli is now vendored in pip](https://github.com/pypa/pip/pull/10035), hence this testing PR. I'm unsure which TOML parsers we should support. What is your opinion on this?

**Comment by frenzymadness** [comment]
During working on this, I've discovered that our support for pytoml is not complete :( The problem is that we do not have any negative tests for this https://github.com/thoth-station/micropipenv/blob/d0c37c1bf0aadf5149aebe2df0bf1cb12ded4c40/micropipenv.py#L239-L245
What I mean is that pytoml also does not have `TomlDecodeError` but we don't know about it because the except clause is not evaluated until an exception is raised in the try block.

**Comment by frenzymadness** [comment]
Take a look at my implementation. I'm not sure why some tests failed. Will try to run the same envs locally.

**Comment by frenzymadness** [comment]
It seems to me that the very old pip does not work well with the latest setuptools so I'll have to find a way how to pin setuptools to some older version which won't be an easy task. I don't want to create a new variable for that. I'd rather somehow merge that information to one variable specifying all the dependencies at once.

**Comment by frenzymadness** [comment]
It seems that `setuptools<40` is too old for Python 3.9, testing again with `<60`.

**Comment by frenzymadness** [comment]
Almost all green. pre-commit is complaining about trailing whitespace in a file we haven't touched here but I'll fix it in the next commit to make it happy.

**Comment by frenzymadness** [comment]
@fridex I cannot request a review from you because you are the author of this PR so I've assigned it to you.

**Review by fridex — COMMENTED** [review]
This looks very nice! Thanks for taking care of this. 👍🏻 LGTM

**Comment by fridex** [comment]
@frenzymadness I'm happy to have this merged if you are fine with that.

**Pull request merged**
