### PR TITLE
Add CI use case of micropipenv

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by frenzymadness — COMMENTED** [review]
The change looks good to me. I've noticed that some lines in this list have full stops and some don't. It would be nice to unify it given the fact that all of them are full sentences. This might be the opportunity to do it.

**Comment by frenzymadness** [comment]
And it seems we need to add the latest pip 21.1.2.

**Comment by fridex** [comment]
@frenzymadness thanks for the review. Adjusted and opened https://github.com/thoth-station/micropipenv/pull/176 as you suggested 👍🏻

**Review by frenzymadness — APPROVED** [review]
Perfect!

**Pull request merged**
