### PR TITLE
WIP: Python2 support

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] Yes
- [ ] No

Fixes: #19

### CODE REVIEW

**Comment by fridex** [comment]
> https://github.com/thoth-station/micropipenv/blob/a021bb6fbee5a4e471d1674bf64ff69f0ba0fa17/micropipenv.py#L130
> 
> 
> can you add a period (.) at the end of the line. :)

https://github.com/thoth-station/micropipenv/pull/21

**Comment by harshad16** [comment]
recheck

**Comment by frenzymadness** [comment]
There are more issues than I thought. For example:
* tests have hardcoded "python3", "pip3"
* `redirect_stdout` has to be reimplemented in a similar way as `cwd` (does not exist on Python 2)
* `mypy` is not supported on Python 2

I've ported a part of the codebase (see the latest commits) and now it seems that it partially works. Some tests also pass (21 failed, 18 passed, 1 error) and it seems to me that the remaining tests fail on differences between actual vs. expected output, for example:
```
>               assert f.read() == expected
E               assert "--index-url ...rsion < '4'\n" == "--index-url h...rsion < '4'\n"
E                   --index-url https://pypi.org/simple
E                   --extra-index-url https://tensorflow.pypi.thoth-station.ninja/
E                   --trusted-host tensorflow.pypi.thoth-station.ninja
E                   #
E                   # Default dependencies
E                   #
E                 + certifi==2019.11.28
E                 + chardet==3.0.4
E                   idna==2.8
E                   requests==2.22.0
E                 - certifi==2019.11.28
E                 - chardet==3.0.4
```
This has to be investigated more.

It would be also very nice to add tox configuration and move the pytest settings from setup.py to tox.ini/pyproject.toml - in a separated PR before we finish this one as it helps with testing and setting environments in a different way for Py2 and Py3.

But, first of all, as it seems that it won't be that easy, do you still want to support Python 2?

**Comment by fridex** [comment]
@frenzymadness thanks for the work on this! :+1: 

> But, first of all, as it seems that it won't be that easy, do you still want to support Python 2?

We don't have Python2 interest, it's EOL for us. Would Python2 efforts on your (Python s2i) front make anything easier?

**Comment by frenzymadness** [comment]
I completely understand you. I spent years making software compatible with Python 3 and I don't want to work other way around. I've summarized our possibilities in https://github.com/sclorg/s2i-python-container/issues/368

**Comment by fridex** [comment]
@frenzymadness I will close this based on our meeting today. Let's keep it in the history of Internet if we would change our minds...

Thanks for your time on this.

**Pull request closed without merging**
