### PR TITLE
Version 0.3.0

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Depends-On: #93
Fixes: #77

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Converting to draft until #93 gets merged.

**Comment by fridex** [comment]
Discarding WIP. @frenzymadness PTAL - I'll publish the new release if you are OK with it

**Comment by fridex** [comment]
The release is available on [PyPI](https://pypi.org/project/micropipenv/0.3.0/) as well as on [GitHub](https://github.com/thoth-station/micropipenv/releases/tag/v0.3.0). Thanks!

**Comment by frenzymadness** [comment]
Updates for Fedora 31 and 32:
* https://bodhi.fedoraproject.org/updates/FEDORA-2020-efd7473127
* https://bodhi.fedoraproject.org/updates/FEDORA-2020-134959625e

**Comment by fridex** [comment]
> Updates for Fedora 31 and 32:
> 
> * https://bodhi.fedoraproject.org/updates/FEDORA-2020-efd7473127
> * https://bodhi.fedoraproject.org/updates/FEDORA-2020-134959625e

:clap: nice, thanks! :+1:

**Pull request merged**
